name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "🎊 Thank-you for submitting your first issue. If you require any help, please contact @kinda-raffy."
        pr-message: "🎊 Thank-you for submitting your first pull request. If you require any help, please contact @kinda-raffy."
